### ISSUE TITLE
extension not work on website auto.plius.lt

### ISSUE THREAD

**Issue by devwitalik** [rudiedirkx/Copyables#8]
Example URL: http://auto.plius.lt/skelbimai/opel-astra-1-7-l-universalas-2008-dyzelinas-4522619.html
Steps to reproduce the problem: choose any car from site, and try to download any picture of the car through Copyables extension.

you can add a feature to download pictures from the website?

**Comment by rudiedirkx** [comment]
The first image under the cursor is the arrow. Or actually, the first element under the cursor that consists of an image, is the arrow. This extension does exactly that: find the top most element with an image and open it. In this case, it's always the arrow.

I wouldn't know how to 'fix' it... Copyables doesn't know where an image ends, or how opaque/transparent it is. If you have an idea, please tell, because it would make sense: click on the **image** you want to open, not the **element**.

Sorry.

**Comment by rudiedirkx** [comment]
No more arrow. Works.
